### ISSUE TITLE
endofbuffer

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#3]
can you highlight EndOfBuffer to completely hide the tildes?

**Comment by ishan9299** [comment]
you can use the fillchars like over [here](https://github.com/wincent/wincent/blob/3e4a81a313ea212152e0a80026fb25bc4d0cc43f/aspects/vim/files/.vim/plugin/settings.vim#L48) to suppress ~ at eob.
I have my config in lua so I have
`o.fillchars = 'diff:∙,fold:·,vert:│,eob: ' -- characters used to fill statuslines and seperators`

**Comment by alok** [comment]
Can you set the theme to hide the tildes via the lua equivalent of

`hi! EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg`?

**Comment by ishan9299** [comment]
this could work but I don't want to implement this because there could be someone who might need the ~ at the end. It helps as a visual aid to know if we have empty lines at the end of the buffer for someone who doesn't use line numbers plus there is a setting available to change it if you want. Closing.

**Comment by ishan9299** [comment]
You can also look up the link I posted above pasting that option in you init.vim or init.lua. It will hide ~ at the end of buffer.
